use std::collections::HashMap;
use std::fs;

use chrono::{DateTime, Duration, Utc};

use crate::config::Config;
use crate::db::Database;
use crate::db::commit_store;
use crate::db::repo_store;
use crate::health::compute_health;

pub fn run(config: &Config) -> anyhow::Result<()> {
    let db = Database::open(&config.db_path())?;
    let index_path = config.index_path()?;

    let repos = db.tx(|conn| repo_store::get_all_repos(conn))?;
    if repos.is_empty() {
        anyhow::bail!("No repos synced. Run `pidx sync` first.");
    }

    let thirty_days_ago = (Utc::now() - Duration::days(30))
        .format("%Y-%m-%dT%H:%M:%SZ")
        .to_string();

    // Build category display name mapping from config
    let category_titles: HashMap<&str, &str> = config
        .categories
        .iter()
        .map(|c| (c.key.as_str(), c.title.as_str()))
        .collect();

    // Group repos by category, preserving config order
    let mut category_order: Vec<String> = Vec::new();
    let mut by_category: HashMap<String, Vec<RepoIndexEntry>> = HashMap::new();

    // Build config description overrides
    let config_descriptions: HashMap<&str, &str> = config
        .repos
        .iter()
        .filter_map(|r| r.description.as_deref().map(|d| (r.name.as_str(), d)))
        .collect();

    // Use config order for repos (which determines category encounter order)
    let config_repo_order: HashMap<&str, usize> = config
        .repos
        .iter()
        .enumerate()
        .map(|(i, r)| (r.name.as_str(), i))
        .collect();

    let mut sorted_repos = repos.clone();
    sorted_repos.sort_by_key(|r| config_repo_order.get(r.name.as_str()).copied().unwrap_or(999));

    for repo in &sorted_repos {
        let cat = repo.category.clone().unwrap_or_else(|| "other".to_string());

        if !by_category.contains_key(&cat) {
            category_order.push(cat.clone());
        }

        let commits_30d = db.tx(|conn| {
            commit_store::count_commits_since(conn, repo.id, &thirty_days_ago)
        })?;

        let last_pushed: Option<DateTime<Utc>> = repo
            .pushed_at
            .as_deref()
            .and_then(|s| s.parse().ok());

        let health = compute_health(last_pushed, commits_30d, repo.open_issues as u32);

        by_category.entry(cat).or_default().push(RepoIndexEntry {
            name: repo.name.clone(),
            owner: repo.owner.clone(),
            language: repo.language.clone().unwrap_or_else(|| "-".to_string()),
            description: config_descriptions
                .get(repo.name.as_str())
                .map(|s| s.to_string())
                .or_else(|| repo.description.clone())
                .unwrap_or_default(),
            health_label: health.label.as_str().to_string(),
            health_score: health.total,
        });
    }

    // Generate README
    let mut out = String::new();
    out.push_str("# Project Index\n\n");
    out.push_str("A catalog of my open-source projects.\n\n");
    out.push_str(&format!(
        "<!-- Generated by pidx on {} -->\n\n",
        Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));
    out.push_str("## Active Projects (2026)\n\n");

    for cat in &category_order {
        let title = category_titles
            .get(cat.as_str())
            .copied()
            .unwrap_or(cat.as_str());

        out.push_str(&format!("### {title}\n\n"));
        out.push_str("| Project | Language | Description |\n");
        out.push_str("|---------|----------|-------------|\n");

        if let Some(entries) = by_category.get(cat) {
            for entry in entries {
                out.push_str(&format!(
                    "| [{}](https://github.com/{}/{}) | {} | {} |\n",
                    entry.name, entry.owner, entry.name, entry.language, entry.description,
                ));
            }
        }

        out.push('\n');
    }

    fs::write(&index_path, &out)?;
    println!("Updated index at {}", index_path.display());

    Ok(())
}

struct RepoIndexEntry {
    name: String,
    owner: String,
    language: String,
    description: String,
    health_label: String,
    health_score: f64,
}
